import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google"
import { cn } from "@/lib/utils"
import Menu from "@/components/menu";
import { ThemeProvider } from "@/components/theme-provider"
import { ScrollArea} from "@/components/ui/scroll-area";
import Sidebar from "@/components/menu/sidebar";




 
export const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Youtube App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          roboto.className
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="ligth"
            enableSystem
            disableTransitionOnChange
          >
          <div className="min-h-screen flex flex-col p-0  font-sans antialiased">

          
              <div className="py-0 px-5">
                <Menu/>
              </div>
              <div className="flex">
                <div className="w-[22%] flex-shrink-0">
                  <ScrollArea className="pr-9 py-4 h-[90vh] w-full">
                  <Sidebar/>
                  </ScrollArea>
                </div>
              <div className="flex-1"> {children}</div>
              </div>
            </div>
            
         
          
            </ThemeProvider>
          </body>
    </html>
  );
}
